### PR TITLE
HOWTO maven blog post 

### PR DESCRIPTION
**Pull request by Sammers21**
HOWTO maven blog post

### CODE REVIEW

**Comment by Sammers21** [comment]
@g4s8, @yegor256 review the PR, please.

**Comment by yegor256** [comment]
@Sammers21 I would add some intro first. Check this one for example: https://www.yegor256.com/2014/08/19/how-to-release-to-maven-central.html and this one: https://www.yegor256.com/2015/09/07/maven-repository-amazon-s3.html I would also write from yourself, like "I suggest, ..."

**Comment by Sammers21** [comment]
> I would also write from yourself, like "I suggest, ..."

@yegor256, Since it is not my personal blog, I would not do it.

**Comment by yegor256** [comment]
@Sammers21 any blog is personal. Otherwise, it's not fun to read.

**Comment by Sammers21** [comment]
@yegor256, can you review the PR one more time, please?

**Comment by yegor256** [comment]
@Sammers21 it looks super boring to me. It's not an instruction page, it's a blog. It should tell a story. Entertain me. Educate me.)

**Comment by Sammers21** [comment]
> It should tell a story. Entertain me. Educate me.)

@yegor256, Why a HOWto article should do this? I think of them as of tutorials. Quick and understandable set of instructions for achieving a specific goal. 

Examples: 

https://blog.sonatype.com/using-nexus-3-as-your-repository-part-1-maven-artifacts
https://ma.ttias.be/socks-proxy-linux-ssh-bypass-content-filters/

**Comment by yegor256** [comment]
@Sammers21 I'm a reader. I start and read: "In this blog post i will explain how to install Artipie and configure it as a maven repository.". I ask myself, what is "maven"? Why do I need to install Artipie (whatever it is) and configure it as some repository? WTF am I reading now? OK, I close. Bye, bye.

**Comment by Sammers21** [comment]
@yegor256, can you review the PR one more time, please?

**Pull request closed without merging**
