### PR TITLE
#14 - November blog post

### LINKED ISSUE #14: November release notes
We need to publish November release notes article to give overview of changes made in Artipie during the month

### PR DESCRIPTION
**Pull request by olenagerasimova**
Closes #14 
I've added November blog post

### CODE REVIEW

**Comment by olenagerasimova** [comment]
@olegmoz please, take a look, did I've missed smth important?

**Comment by olegmoz** [comment]
@olenagerasimova thanks, nice summary. I think that this month added tests for RPM incremental update and so the feature became finalized. So I'd mention this. Also we have finished integration tests for Ruby Gems and Helm this month, we may say that all repository types are now covered with end-to-end tests.

**Comment by olenagerasimova** [comment]
@olegmoz thanks, corrected

**Comment by olegmoz** [comment]
@olenagerasimova I have release Artipie version 0.13, it is available on Docker Hub: https://hub.docker.com/layers/artipie/artipie/0.13/images/sha256-a60bf614b915fcb8f62edd854fbade0774fdf0ddf67611d7062652b69470c447?context=explore

Please update the blog post so it all will be ready to be published on Monday

**Comment by olenagerasimova** [comment]
@olegmoz thanks, added link and corrected keywords

**Comment by olegmoz** [comment]
@olenagerasimova thanks, published

**Pull request merged**
